### ISSUE TITLE
Chrome on Win10 blocks Crycker 1.1

### ISSUE THREAD

**Issue by jadbox** [davidvidmar/Crycker#26]
Chrome says: "Crycker.exe" is dangerous so Chrome has blocked it.

Chrome: 83.0.4103.116

**Comment by ghost** [comment]
Firefox too.

**Comment by davidvidmar** [comment]
Looking into this. Freshly compiled version on two (clean) computers result in same binary, but still VirusTotal reports infections.

**Comment by davidvidmar** [comment]
I'll close this as a Duplicate of #27. I'll report the progress there.
