### ISSUE TITLE
Antivirus malware alert

### ISSUE THREAD

**Issue by MiracleToast** [davidvidmar/Crycker#31]
Hello,

Trying to download the compiled binary, but blocked from BitDefender:

Downloads\2def84c6-faf0-44cc-b775-408ce3ec8069.tmp is malware of type Gen:Variant.Bulz.38229

Win10 Pro 21H2, Crycker v1.1, Bitdefender BEST 7.4.3146, engine 7.91286, updated 02/27/2022.

**Comment by davidvidmar** [comment]
Please see #27.
