### ISSUE TITLE
Support for custom currencies

### ISSUE THREAD

**Issue by Logerfo** [davidvidmar/Crycker#8]
BlockchainTickerData class suggests other currencies can be used, if the select provider supports it. It would be convenient for the user to be able to select any of the available currencies.

**Comment by Logerfo** [comment]
I tried to do it myself, but adding every available currency would be too much and Combobox can only be added as a host control (it cannot be "checked"), so I ran out of not-awful-looking ideas

**Comment by Logerfo** [comment]
Another suggestion: currencies should not be hard coded. The application should read the JSON and dynamically provide the currency options for the user. Being as generic as this would make things easier and maintainable.

**Comment by davidvidmar** [comment]
Hm, that's interesting idea. How about I let users set custom currency in .config file? There are some settings in there that are not available from menu already.

**Comment by Logerfo** [comment]
I think it's a good temporary solution

**Comment by Logerfo** [comment]
https://github.com/davidvidmar/Crycker/pull/11
